pragma solidity ^0.4.24;

import "../coffeecore/Ownable.sol";
import "../coffeeaccesscontrol/ConsumerRole.sol";
import "../coffeeaccesscontrol/FarmerRole.sol";
import "../coffeeaccesscontrol/DistributorRole.sol";
import "../coffeeaccesscontrol/RetailerRole.sol";

contract SupplyChain is FarmerRole, DistributorRole, RetailerRole, ConsumerRole, Ownable {

    uint  sku;

    mapping(uint => Item) items;

    enum State
    {
        Growing,
        Harvested,
        Processed,
        Packed,
        ForSale,
        Sold,
        Shipped,
        Received,
        Purchased
    }

    // Define a struct 'Item' with the following fields:
    struct Item {
        uint sku;  // Stock Keeping Unit (SKU)
        uint upc; // Universal Product Code (UPC), generated by the Farmer, goes on the package, can be verified by the Consumer
        address ownerID;  // Metamask-Ethereum address of the current owner as the product moves through 8 stages
        address originFarmerID; // Metamask-Ethereum address of the Farmer
        string originFarmName; // Farmer Name
        string originFarmInformation;  // Farmer Information
        string originFarmLatitude; // Farm Latitude
        string originFarmLongitude;  // Farm Longitude
        string productNotes; // Product Notes
        uint productPrice; // Product Price
        State itemState;  // Product State as represented in the enum above
        address distributorID;  // Metamask-Ethereum address of the Distributor
        address retailerID; // Metamask-Ethereum address of the Retailer
        address consumerID; // Metamask-Ethereum address of the Consumer
    }

    event Harvested(uint upc);
    event Processed(uint upc);
    event Packed(uint upc);
    event ForSale(uint upc);
    event Sold(uint upc);
    event Shipped(uint upc);
    event Received(uint upc);
    event Purchased(uint upc);

    modifier verifyCaller (address _address) {
        require(msg.sender == _address);
        _;
    }

    modifier itemOwner (uint _upc) {
        require(items[_upc].ownerID == msg.sender);
        _;
    }

    modifier paidEnough(uint _upc) {
        require(msg.value >= items[_upc].productPrice);
        _;
    }

    modifier checkValue(uint _upc) {
        _;
        uint _price = items[_upc].productPrice;
        uint amountToReturn = msg.value - _price;
        msg.sender.transfer(amountToReturn);
    }

    modifier growing(uint _upc) {
        require(_isState(_upc, State.Growing));
        _;
    }

    modifier harvested(uint _upc) {
        require(_isState(_upc, State.Harvested));
        _;
    }

    modifier processed(uint _upc) {
        require(_isState(_upc, State.Processed));
        _;
    }

    modifier packed(uint _upc) {
        require(_isState(_upc, State.Packed));
        _;
    }

    modifier forSale(uint _upc) {
        require(_isState(_upc, State.ForSale));
        _;
    }

    modifier sold(uint _upc) {
        require(_isState(_upc, State.Sold));
        _;
    }

    modifier shipped(uint _upc) {
        require(_isState(_upc, State.Shipped));
        _;
    }

    modifier received(uint _upc) {
        require(_isState(_upc, State.Received));
        _;
    }

    modifier purchased(uint _upc) {
        require(_isState(_upc, State.Purchased));
        _;
    }

    constructor() public {
        sku = 1;
    }

    function harvestItem(
        uint _upc,
        address _originFarmerID,
        string _originFarmName,
        string _originFarmInformation,
        string _originFarmLatitude,
        string _originFarmLongitude,
        string _productNotes
    ) public isFarmer verifyCaller(_originFarmerID) growing(_upc)
    {
        sku = sku + 1;
        items[_upc] = Item(
            sku,
            _upc,
            _originFarmerID,
            _originFarmerID,
            _originFarmName,
            _originFarmInformation,
            _originFarmLatitude,
            _originFarmLongitude,
            _productNotes,
            0,
            State.Harvested
        );

        emit Harvested(_upc);

    }

    function processItem(uint _upc) public isFarmer itemOwner(_upc) harvested(_upc)
    {
        items[_upc].itemState == State.Processed;
        emit Processed(_upc);
    }

    function packItem(uint _upc) public isFarmer itemOwner(_upc) processed(_upc)
    {
        items[_upc].itemState == State.Packed;
        emit Packed(_upc);
    }

    function sellItem(uint _upc, uint _price) public isFarmer itemOwner(_upc) packed(_upc)
    {
        items[_upc].itemState == State.ForSale;
        items[_upc].productPrice == _price;

        emit ForSale(_upc);
    }

    function buyItem(uint _upc) public payable isDistributor forSale(_upc) paidEnough(_upc)
    {
        items[_upc].itemState == State.Sold;
        items[_upc].distributorID == msg.sender;
        items[_upc].ownerID == msg.sender;

        emit Sold(_upc);
    }

    function shipItem(uint _upc) public isDistributor itemOwner(_upc) sold(_upc)
    {
        items[_upc].itemState == State.Shipped;

        emit Shipped(_upc);
    }

    function receiveItem(uint _upc) public isRetailer shipped(_upc)
    {
        items[_upc].itemState == State.Received;
        items[_upc].retailerID == msg.sender;
        items[_upc].ownerID == msg.sender;

        emit Received(_upc);

    }

    function purchaseItem(uint _upc) public isConsumer received(_upc)
    {
        items[_upc].itemState == State.Purchased;
        items[_upc].consumerID == msg.sender;
        items[_upc].ownerID == msg.sender;

        emit Purchased(_upc);
    }

    // Define a function 'fetchItemBufferOne' that fetches the data
    function fetchItemBufferOne(uint _upc) public view returns
    (
        uint itemSKU,
        uint itemUPC,
        address ownerID,
        address originFarmerID,
        string originFarmName,
        string originFarmInformation,
        string originFarmLatitude,
        string originFarmLongitude
    )
    {
        // Assign values to the 8 parameters


        return
        (
        itemSKU,
        itemUPC,
        ownerID,
        originFarmerID,
        originFarmName,
        originFarmInformation,
        originFarmLatitude,
        originFarmLongitude
        );
    }

    // Define a function 'fetchItemBufferTwo' that fetches the data
    function fetchItemBufferTwo(uint _upc) public view returns
    (
        uint itemSKU,
        uint itemUPC,
        string productNotes,
        uint productPrice,
        uint itemState,
        address distributorID,
        address retailerID,
        address consumerID
    )
    {
        // Assign values to the 9 parameters


        return
        (
        itemSKU,
        itemUPC,
        productNotes,
        productPrice,
        itemState,
        distributorID,
        retailerID,
        consumerID
        );
    }

    function _isState(uint _upc, State _state) internal returns (bool) {
        return items[_upc].itemState == _state;
    }
}
